# Generated by Django 5.2 on 2025-04-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=20)),
                ('license_details', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('alternate_contact', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Backup', 'Backup')], max_length=10)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='billing.category')),
            ],
        ),
    ]
