# Generated by Django 5.2 on 2025-05-28 09:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_company_item_itemcategory_itemtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('type_name', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price_per_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
    ]
