# Generated by Django 5.2 on 2025-05-29 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_purchase_discount_purchase_grand_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
